1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

-Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

# 1. Sayılardan oluşan tek boyutlu array oluşturma (Veri tipi: Integer)
array = np.array([5, 15, 25, 35, 45], dtype=int)

print("--- Array Bilgileri ---")
print("Oluşturulan Array:", array)
print("Veri Tipi (dtype):", array.dtype)

# 2. Oluşturulan arrayin boyut ve eleman sayısı bilgilerini alma
print(f"Array'in Boyutu (ndim): {array.ndim}")
print(f"Array'in Eleman Sayısı (size): {array.size}")
print(f"Array'in Şekli (shape): {array.shape}")


--- Array Bilgileri ---
Oluşturulan Array: [ 5 15 25 35 45]
Veri Tipi (dtype): int64
Array'in Boyutu (ndim): 1
Array'in Eleman Sayısı (size): 5
Array'in Şekli (shape): (5,)


2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

In [2]:
import numpy as np

# İki boyutlu array oluşturma
iki_boyutlu_array = np.array([
    [1, 2, 6, 7],
    [4, 3, 9, 5]
])

# Üç boyutlu array oluşturma
uc_boyutlu_array = np.array([
    [[7, 5, 14], [21, 8, 11]],
    [[8, 6, 20], [14, 3, 9]]
])

print("--- İki Boyutlu Array Bilgileri ---")
print("Array:\n", iki_boyutlu_array)
print("Boyut (ndim):", iki_boyutlu_array.ndim)
print("Eleman Sayısı (size):", iki_boyutlu_array.size)
print("Şekil (shape):", iki_boyutlu_array.shape)
print(f"Satır: {iki_boyutlu_array.shape[0]}, Sütun: {iki_boyutlu_array.shape[1]}")

print("\n--- Üç Boyutlu Array Bilgileri ---")
print("Array:\n", uc_boyutlu_array)
print("Boyut (ndim):", uc_boyutlu_array.ndim)
print("Eleman Sayısı (size):", uc_boyutlu_array.size)
print("Şekil (shape):", uc_boyutlu_array.shape)
print(f"Derinlik: {uc_boyutlu_array.shape[0]}, Satır: {uc_boyutlu_array.shape[1]}, Sütun: {uc_boyutlu_array.shape[2]}")


--- İki Boyutlu Array Bilgileri ---
Array:
 [[1 2 6 7]
 [4 3 9 5]]
Boyut (ndim): 2
Eleman Sayısı (size): 8
Şekil (shape): (2, 4)
Satır: 2, Sütun: 4

--- Üç Boyutlu Array Bilgileri ---
Array:
 [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut (ndim): 3
Eleman Sayısı (size): 12
Şekil (shape): (2, 2, 3)
Derinlik: 2, Satır: 2, Sütun: 3


3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [3]:
import numpy as np

print(f"İki boyutlu arraydaki 2 elemanı: {iki_boyutlu_array[0, 1]}")

print(f"İki boyutlu arraydaki 7 elemanı: {iki_boyutlu_array[0, 3]}")

print(f"Üç boyutlu arraydaki 9 elemanı: {uc_boyutlu_array[1, 1, 2]}")

print(f"Üç boyutlu arraydaki 5 elemanı: {uc_boyutlu_array[0, 0, 1]}")

İki boyutlu arraydaki 2 elemanı: 2
İki boyutlu arraydaki 7 elemanı: 7
Üç boyutlu arraydaki 9 elemanı: 9
Üç boyutlu arraydaki 5 elemanı: 5


4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

In [4]:
import numpy as np

print(f"İki boyutlu arraydaki 2,6 elemanları: {iki_boyutlu_array[0, 1:3]}")

print(f"İki boyutlu arraydaki 3,9,5 elemanları: {iki_boyutlu_array[1, 1:]}")

print(f"Üç boyutlu arraydaki 21,8,11 elemanları: {uc_boyutlu_array[0, 1, :]}")

print(f"Üç boyutlu arraydaki 6,20 elemanları: {uc_boyutlu_array[1, 0, 1:]}")

İki boyutlu arraydaki 2,6 elemanları: [2 6]
İki boyutlu arraydaki 3,9,5 elemanları: [3 9 5]
Üç boyutlu arraydaki 21,8,11 elemanları: [21  8 11]
Üç boyutlu arraydaki 6,20 elemanları: [ 6 20]


5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [5]:
import numpy as np

# 5 satır 3 sütunluk sıfırlardan oluşan array
zeros_array = np.zeros((5, 3), dtype=int)
print("--- Sıfırlardan Oluşan Array ---")
print(zeros_array)

# 5 satır 3 sütunluk birlerden oluşan array
ones_array = np.ones((5, 3), dtype=int)
print("\n--- Birlerden Oluşan Array ---")
print(ones_array)

--- Sıfırlardan Oluşan Array ---
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

--- Birlerden Oluşan Array ---
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
import numpy as np

# Satır bazında birleştirme (dikey birleştirme)
# np.vstack() veya np.concatenate(axis=0) kullanılabilir
row_concatenated_array = np.vstack((zeros_array, ones_array))
print("--- Satır Bazında Birleştirilmiş Array ---")
print(row_concatenated_array)

# Sütun bazında birleştirme (yatay birleştirme)
# np.hstack() veya np.concatenate(axis=1) kullanılabilir
col_concatenated_array = np.hstack((zeros_array, ones_array))
print("\n--- Sütun Bazında Birleştirilmiş Array ---")
print(col_concatenated_array)

--- Satır Bazında Birleştirilmiş Array ---
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

--- Sütun Bazında Birleştirilmiş Array ---
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
